export const GET_PRODUCTS_LIST = "FETCH_PRODUCTS_LIS";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CARD";
export const DELETE_PRODUCT_FROM_CART = "DELETE_PRODUCT_FROM_CART";
export const INCREMENT_PRODUCT = "INCREMENT_PRODUCT";
export const DECREMENT_PRODUCT = "DECREMENT_PRODUCT";
